/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_final_ans;

import java.awt.Color;

/**
 *
 * @author yo breyner saul
 */
public class INICIO extends javax.swing.JFrame {

    /**
     * Creates new form INICIO
     */
    public INICIO() {
        initComponents();
           getContentPane().setBackground(Color.DARK_GRAY);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        estudiante = new javax.swing.JButton();
        invitado = new javax.swing.JButton();
        profesor = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INDIQUE  SU ROL EN LA UNIVERSIDAD");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        estudiante.setBackground(new java.awt.Color(51, 204, 255));
        estudiante.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        estudiante.setForeground(new java.awt.Color(255, 255, 255));
        estudiante.setText("ESTUDIANTE");
        estudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estudianteActionPerformed(evt);
            }
        });
        getContentPane().add(estudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 260, 40));

        invitado.setBackground(new java.awt.Color(51, 204, 255));
        invitado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        invitado.setForeground(new java.awt.Color(255, 255, 255));
        invitado.setText("INVITADO");
        invitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invitadoActionPerformed(evt);
            }
        });
        getContentPane().add(invitado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 260, 40));

        profesor.setBackground(new java.awt.Color(51, 204, 255));
        profesor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        profesor.setForeground(new java.awt.Color(255, 255, 255));
        profesor.setText("PROFESOR");
        profesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profesorActionPerformed(evt);
            }
        });
        getContentPane().add(profesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 260, 40));

        jLabel5.setBackground(new java.awt.Color(51, 204, 255));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 40));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 60, 160));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 60, 160));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 380, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profesorActionPerformed
        dispose();
        PROFESORES profesores = new PROFESORES();
        profesores.setVisible(true);
    }//GEN-LAST:event_profesorActionPerformed

    private void invitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invitadoActionPerformed
    dispose();
        Invitados invitados = new Invitados();
        invitados.setVisible(true);
    }//GEN-LAST:event_invitadoActionPerformed

    private void estudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estudianteActionPerformed
        dispose();
        Log_Estudiante modulo_salas = new Log_Estudiante();
        modulo_salas.setVisible(true);
    }//GEN-LAST:event_estudianteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INICIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INICIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INICIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INICIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INICIO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton estudiante;
    private javax.swing.JButton invitado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton profesor;
    // End of variables declaration//GEN-END:variables
}
